site_name: "Termynal"
site_url: "https://pypi.org/project/termynal"
site_description: ""

repo_name: "termynal"
repo_url: "https://github.com/daxartio/termynal"
edit_uri: "edit/main/docs/"

copyright: "Copyright &copy; 2021 Danil Akhtarov <daxartio@gmail.com>"

nav:
  - "Home": README.md

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: yellow

plugins:
  - termynal
  - search:
      lang: en

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - termynal:
      prompt_literal_start:
        - "$ "
        - "&gt; "
        - "&gt;&gt;&gt; "
