name: Github pages

on:
  push:
    paths:
      - "README.md"
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pip install poetry==1.3.2

      - name: Install python dependencies
        run: make install-docs

      - name: Move README
        run: cp README.md docs/

      - name: Generate docs
        run: make docs

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
